name: firebase_auth_repository
description: wrapper for firebase authentication
version: 0.0.1
#homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: any
  firebase_auth: any
  firebase_core: any
  flutter:
    sdk: flutter
  google_sign_in: any
  meta: any
  very_good_analysis: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: any