name: firebase_auth_repository
description: wrapper for firebase authentication
version: 0.0.1
#homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.4
  meta: ^1.3.0
  very_good_analysis: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0